services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      DOMAINS: "${DOMAINS} -> http://web:8000"
      STAGE: $STAGE
      CLIENT_MAX_BODY_SIZE: 10M
    volumes:
      - ./docker/org-chimata-ssl-certs:/var/lib/https-portal

  web:
    image: nginx:latest
    ports:
      - "8000:8000"
    depends_on:
      - api
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  api:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    user: "${UID_GID}"

  container_worker:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    restart: always
    command: php artisan queue:listen

  client:
    build: ./docker/node
    tty: true
    volumes:
      - ./src:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "${NPM_RUN_COMMAND}"
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8.4
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
    entrypoint: >
      /bin/sh -c " mc alias set myminio http://minio:9000 user password; mc mb myminio/develop; mc anonymous set public myminio/develop; "

volumes:
  https-portal-data:
  mysql_data:
  minio_data:
