FROM mysql:8.4

# MySQLの設定を追加（必要に応じて）
COPY ./docker/mysql/my.cnf /etc/mysql/conf.d/my.cnf

# ヘルスチェック設定
HEALTHCHECK --interval=5s --timeout=5s --retries=3 CMD mysqladmin ping -h localhost -u root --password=${MYSQL_ROOT_PASSWORD} || exit 1

# タイムゾーン設定
ENV TZ=Asia/Tokyo

# ポート設定
EXPOSE 3306 