services:
  # Laravel API サービス
  - type: web
    name: api
    plan: free
    runtime: docker
    dockerfilePath: docker/php/render_Dockerfile
    dockerContext: .
    buildCommand: cd app && composer install --no-interaction --optimize-autoloader && php artisan config:cache
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
            type: web
            name: api
            envVarKey: RENDER_EXTERNAL_URL
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

  # Laravel queue worker
  - type: worker
    name: container-worker
    plan: free
    runtime: docker
    dockerfilePath: docker/php/render_Dockerfile
    dockerContext: .
    buildCommand: cd app && composer install --no-interaction --optimize-autoloader && php artisan config:cache
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

  # Next.js クライアントアプリ
  - type: web
    name: client
    plan: free
    runtime: docker
    dockerfilePath: docker/node/render_Dockerfile
    dockerContext: .
    buildCommand: cd src && npm install && npm run build
    envVars:
      - key: NEXT_PUBLIC_APP_ENV
        value: production
      - key: NEXT_PUBLIC_APP_ROOT
        fromService:
            type: web
            name: client
            envVarKey: RENDER_EXTERNAL_URL
      - key: NEXT_PUBLIC_API_ROOT
        fromService:
            type: web
            name: api
            envVarKey: RENDER_EXTERNAL_URL
      - key: STRIPE_KEY
        sync: false

  # MySQL コンテナ（pserv）
  - type: pserv
    name: mysql
    runtime: docker
    dockerfilePath: Dockerfile.mysql
    dockerContext: .
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false